# Generated by Django 4.2.2 on 2024-03-03 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexusapp', '0005_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='channel_profile_pictures'),
        ),
    ]
