# Generated by Django 4.2.2 on 2024-03-04 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nexusapp', '0007_alter_channel_from_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='date',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='message',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='video',
        ),
        migrations.CreateModel(
            name='Channel_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('video', models.FileField(blank=True, null=True, upload_to='channel_videos')),
                ('image', models.ImageField(blank=True, null=True, upload_to='channel_images')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='nexusapp.channel')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
